### ISSUE TITLE
Regarding Deleting message

### ISSUE THREAD

**Issue by piccotalent-127** [vsevex/whixp#30]
Hello
Is there way that we can delete a message in a group or a 1 to 1 chat and the deletion event is received on both ends

**Comment by vsevex** [comment]
Hi, sorry for late response.

I have completely changed the structure of the package, in the next days I will publish all the use cases related to Roster Management as well as messaging functionality peer to peer and for MUC. For the old package (which is available in pub.dev) is not providing comprehensive work with rosters. This version will give you possibilty of management roster easily as well as other functionalities of XMPP.

But, unfortunately I cannot give you support for the old one at the moment.

**Comment by mehmetgencdal** [comment]
@piccotalent-127 I have a problem and I couldn't reach the publisher. Can you help me about the problem?
