### ISSUE TITLE
Any release date for new version?

### ISSUE THREAD

**Issue by bugragoksu** [vsevex/whixp#35]
Hello!

First of all thank you for this great project. I can't wait to use new version of whixp.

I'm developing a chat application so after a bit search i decided to use this package. But i want to wait to first stable release of whixp.

So, is there any decided date to release new version?

**Comment by vsevex** [comment]
Just published a new version of the package, but it is not stable yet. Please consider this when you are using the package and if there is any bug or enhancement recommendation, please do not hesitate to open an issue.
